### ISSUE TITLE
Standardize repository information

### ISSUE THREAD

**Issue by zenorocha** [dracula/google-chrome#1]
Hello @nickimola!

Thanks for transferring the repository, could you follow all the conventions we have for the repositories based on https://github.com/dracula/template? You can also check the other ones to see if it matches with yours https://github.com/dracula.

Let me know when you finish it :)

**Comment by nickimola** [comment]
ok, will do as soon as i can. Thanks

2017-03-13 15:59 GMT+00:00 Zeno Rocha <notifications@github.com>:

**Comment by nickimola** [comment]
Hi, it should be done now. The only thing that is missing from the readme
file is the link to the website, as i don't know the url yet.


2017-03-13 16:02 GMT+00:00 Nick <nickimola@gmail.com>:

**Comment by zenorocha** [comment]
Awesome, could you update the same to `chrome`? That way we can follow the same pattern we used for `chrome-devtools`. Thanks!

**Comment by nickimola** [comment]
Hi, it's done. Thanks

2017-03-14 16:07 GMT+00:00 Zeno Rocha <notifications@github.com>:
