### ISSUE TITLE
Downloads banner color broken

### ISSUE THREAD

**Issue by iam-cult** [dracula/google-chrome#12]
Upon updating my theme, I was greeted with a bright white downloads banner as shown below. This also affects the banner for installing themes.
![Screen Shot 2021-03-25 at 09 08 23](https://user-images.githubusercontent.com/65368815/112477778-ba244400-8d49-11eb-8ba8-83ef249b0ea2.png)
![Screen Shot 2021-03-25 at 09 08 00](https://user-images.githubusercontent.com/65368815/112477811-c27c7f00-8d49-11eb-8e81-da0964dd10b3.png)

**Comment by nickimola** [comment]
Hi
Gonna look into this as soon as I can.
Thanks for reporting

**Comment by iam-cult** [comment]
Seems to also affect the icon that indicates a tab playing sound
![Screen Shot 2021-03-25 at 09 56 00](https://user-images.githubusercontent.com/65368815/112484499-610bde80-8d50-11eb-9f92-7e3cf0790a91.png)

**Comment by iam-cult** [comment]
It seems like this stems from the removal of the "toolbar" value which was the fix to #11

**Comment by nickimola** [comment]
Yes it is, but keeping that value then created a thin gray line than breaks the group colouring (like per the #11 issue)
I need to see if I can create images to use rather then colours for the download bar as well and wee what I can do for the icons

**Comment by iam-cult** [comment]
Yeah, would there be any way to make the gray line transparent, maybe through the "toolbar" value?

**Comment by iam-cult** [comment]
Did some searching around, and the color of these banners and icons seem to be non overwritable, being apparently based on the toolbar value. I know other themes that lack the gray line while still declaring a "toolbar" value, but I have no idea what invokes the line.

**Comment by iam-cult** [comment]
I set the "toolbar" value to [0, 0, 0] and it seemed to fix both the gray bar and the banner issue, but it's weird that the color you used would have somehow caused a bug

**Comment by iam-cult** [comment]
I've set it to [68, 71, 90] instead, which still fits the dracula colorscheme, and I will open a PR
