### ISSUE TITLE
needs a complimentary new tab page

### ISSUE THREAD

**Issue by mgroth0** [dracula/google-chrome#2]
While this does turn the default new tab page into the right color, it flashes white every time since it's not a true new tab override. 

[So I created one](https://github.com/matthew-groth/Dracula-New-Tab-Page) 😈

**Comment by nickimola** [comment]
that it's really good! can we merge this directly into the theme?

**Comment by mgroth0** [comment]
Thanks, and so is your theme! I do not believe Google allows New Tab extensions and themes to be in the same manifest. I tried to combine them, and it didn't work.
