### ISSUE TITLE
Pinned Tabs go Blank

### ISSUE THREAD

**Issue by itguy327** [dracula/google-chrome#23]
After switching to the theme, sometimes the pinned tabs don't have icons or even divisions between the pinned tabs. Can't click on them either

![image](https://user-images.githubusercontent.com/2548760/223762615-16e2e16c-edd1-4b3d-8bc7-a56e7a1d7512.png)

**Comment by tqaw19** [comment]
some tabs look like they're inactive.

**Comment by nickimola** [comment]
Hi

Can you provide more details about this issue?
I have been using this theme since day one, which is almost 8 years now, and never saw this happening to me.

**Comment by itguy327** [comment]
My apologies. I have not had it happen in awhile and my sense is that it
was caused by some other process and was coincidence that I had just
started using the theme.

Thank you for your work
