### ISSUE TITLE
Purple Bar after Chrome update

### ISSUE THREAD

**Issue by Yelleko** [dracula/google-chrome#24]
Hey all,

Not sure if I'm the only one experiencing this but I'm seeing this purple bar after updating chrome:

![image](https://github.com/dracula/google-chrome/assets/26534612/ada3f8b9-9894-4dc7-b3d6-20ac49e1b840)

Chrome version: Version 116.0.5845.96 (Official Build) (arm64)

Thanks!

**Comment by mikeforbes** [comment]
+1

Chrome Version `116.0.5845.96 (Official Build) (64-bit)`

OS: `Debian testing`
deb: `google-chrome-stable_116.0.5845.96-1_amd64.deb`

**Comment by mikeforbes** [comment]
removing
`"theme_toolbar": "images/theme_toolbar.png"` as a workaround and repacking the extension.

**Comment by Yelleko** [comment]
Tried that, same issue for me. What was you order of operations @mikeforbes?

**Comment by mikeforbes** [comment]
1. Clone this repo
2. Remove the entire offending line that references the `theme_toolbar` image & ensure the JSON is valid
3. Remove/uninstall official extension (Settings, Appearance, Use Default seems to work)
4. Repack modified extension:
- Open Google Chrome.
- Tick the checkbox next to Developer mode.
- Click on “Pack extension” in the bar that appears.
- For the “Extension root directory”, browse and select the folder that contains your manifest. json.
- Leave the “Private key file” field empty.
- Click on “Pack Extension”.
5. Drag & drop the created .crx file onto extensions window to install
6. Done?

**Comment by Kevin-McGonigle** [comment]
+1 Chrome Version 116.0.5845.96 (Official Build) (arm64)

**Comment by tophermckee** [comment]
+1 Brave Version 1.57.47 Chromium: 116.0.5845.96 (Official Build) (arm64)

**Comment by nickimola** [comment]
Hi all
Thanks for the report.
I am currently away for a couple of days, will look into this as soon as I get back and will publish an updated version asap
Thanks

**Comment by nickimola** [comment]
Hi
I have just pushed an update which should fix this issue. We are going to lose the purple accent color line on top of the active tab for now, still investigating on how to add it back, but for now the priority was to solve the weird issue with the line where it shouldn't be.
The theme should update as soon as Google approves it.

Thanks

**Comment by Yelleko** [comment]
Awesome, thanks @nickimola!
