### ISSUE TITLE
Download bar white

### ISSUE THREAD

**Issue by ChildishGiant** [dracula/google-chrome#3]
As of a few days ago, the downloads bar at the bottom has turned white.

https://gfycat.com/SpecificGiddyElkhound
![SpecificGiddyElkhound](https://thumbs.gfycat.com/SpecificGiddyElkhound-size_restricted.gif)

**Comment by nickimola** [comment]
Thanks for letting me know, i will investigate as soon as i can

**Comment by nickimola** [comment]
Hi again
I've investigated on this issue and i think it might be a bug in the never version of chrome.
Checking docs shows this:

https://cs.chromium.org/chromium/src/chrome/browser/themes/browser_theme_pack.cc?q=file:chrome/browser/themes+symbol:kOverwritableColorTable&g=0&l=1369

which has a method that says "propagate the toolbar color to the download_shelf bar (which is the white bar in our case) and set the color of it to the same as the toolbar.
This doesn't appear to be the case.

Also, i cannot specify the download_shelf color as per https://cs.chromium.org/chromium/src/chrome/browser/themes/browser_theme_pack.cc?q=file:chrome/browser/themes+symbol:kOverwritableColorTable&g=0&l=261

> "...but not overwritable in the theme file".

The only think i could do for now is to change the text of the downloaded items to be black, but again, this shares the color with the bookmarks text color, and this change will change the bookmarks color to black as well, making them not easy to read.

I think the only thing we can do for now is to wait and see if google fixes it (i've just issued a bug to them about it, let's wait and see now)

**Comment by CollinChaffin** [comment]
After pulling my hair out on this for about the last month I finally dug through the Chromium source as well, and I just Tweeted the fix for this issue that is bound to make you roll your eyes. Link to the Tweet:

https://twitter.com/collinchaffin/status/1118315995276431361

**Comment by ChildishGiant** [comment]
That seems to have worked. I wonder why uninstalling and reinstalling didn't work before
