### ISSUE TITLE
white address text

### ISSUE THREAD

**Issue by shuxiao9058** [dracula/google-chrome#4]
![image](https://user-images.githubusercontent.com/3312525/55311217-eaa3b100-5494-11e9-801f-5ad22bbd8516.png)

**Comment by nickimola** [comment]
Thanks for reporting it.
I will look into this as soon as i can.
Can you provide more details, like chrome version and os?
Cause on windows 10, latest chrome version i can see the color correctly:

![image](https://user-images.githubusercontent.com/9289704/55313058-2889e080-5467-11e9-958f-21a4780b1df3.png)

thanks

**Comment by shuxiao9058** [comment]
when select the address's text, the text to be white color.

**Comment by nickimola** [comment]
which is correct, but the blue highlight is missing in your case.
Do you have any extension that you can try to disable to see if the issue goes away?

![image](https://user-images.githubusercontent.com/9289704/55313539-4dcb1e80-5468-11e9-860f-d576858910ce.png)

**Comment by shuxiao9058** [comment]
It works fine in light mode on macOS, but wrong in dark mode when accent color set to gray.

![image](https://user-images.githubusercontent.com/3312525/55314049-de6f2200-549b-11e9-804b-8bcb1271388c.png)

**Comment by nickimola** [comment]
ok, i will check on a mac as soon as i can

**Comment by shuxiao9058** [comment]
thanks a lot.

**Comment by nickimola** [comment]
Hi again

i've just checked on my mac and I still can't replicate this.
As you can see from the screenshot below everything looks fine

<img width="712" alt="Screenshot 2019-04-01 at 20 28 11" src="https://user-images.githubusercontent.com/9289704/55350776-26eb0780-54bd-11e9-821c-b49d5871d79c.png">

I've used the same settings you suggested:
dark mode with graphite accent color, no extensions and no custom styles + using the latest version of chrome for mac

<img width="357" alt="Screenshot 2019-04-01 at 20 32 22" src="https://user-images.githubusercontent.com/9289704/55350850-471ac680-54bd-11e9-8dec-2b86c5c5f40a.png">

anything else you might have that is different from stock?

thanks
