### ISSUE TITLE
Active tab highlighting does not work with Edge Chromium.

### ISSUE THREAD

**Issue by Dhyfer1** [dracula/google-chrome#8]
Hi.

As you know, any Chrome extension and theme can be installed on the Edge browser, which shares the same open source engine as Chrome, thanks to Chromium. I don't use Chrome, I use Edge because it consumes less resources than Chrome but I can use its extensions and themes.

So I have installed the Dracula theme in Edge, but when I hover the cursor over any tab the colored line does not appear in the tab header as shown in the gif in your repository, and it does not show in the active tab either. I have reinstalled the theme but it is still the same. So, can you do something about it so that the active tab highlighting feature also works with the Edge browser?

That's all.

**Comment by nickimola** [comment]
Hi

The highlight is a new feature that was approved this morning.
I build the new package only a few hours ago and it's under review.
The review time depends on google, so i'll suggest to try again later.
The new version is 2.1

Thanks

**Comment by Dhyfer1** [comment]
> The review time depends on google, so i'll suggest to try again later.
> The new version is 2.1

Ok, I will try it later even though the 2.1 update is already shown in the store but I still don't get the feature I mentioned to you.

![ecBssJyXHv](https://user-images.githubusercontent.com/50301201/107259197-b68f6480-6a0a-11eb-885d-b5b9baa026fe.png)

Well, as I said before I will try again later. If I don't succeed I will write you again, thank you.

**Comment by Dhyfer1** [comment]
Hi.

Several hours later,  the new update does appear as shown in your image. Thank you very much, it looks great. 👍

**Comment by nickimola** [comment]
Great!
Glad it arrived and glad you like my theme!

**Comment by Dhyfer1** [comment]
> Great!
> Glad it arrived and glad you like my theme!

Yes, I like it very much. I hope you can do the same with the vertical tabs. Thank you for your theme. 👍
