### ISSUE TITLE
Weird Looking Top Right Corner

### ISSUE THREAD

**Issue by TheForgottened** [dracula/google-chrome#9]
My Windows version:
![WinVer](https://user-images.githubusercontent.com/46796001/108774636-cf922c80-7557-11eb-91d0-f22a8c3489cf.PNG)
My Chrome version:
![ChromeVer](https://user-images.githubusercontent.com/46796001/108774775-ffd9cb00-7557-11eb-8bd1-cd01900c4948.PNG)
Example:
![Capture](https://user-images.githubusercontent.com/46796001/108774625-ce60ff80-7557-11eb-8b43-46a11758ae45.PNG)

As it can clearly be seen on the screenshots, the 3 buttons on the top right corner look out of place.
I literally only installed the theme, nothing else. I've tried to reinstall the theme and the problem remains.
I can give any information desired / needed to get this fixed, I just hope it isn't me being stupid.

Best regards.

**Comment by nickimola** [comment]
Hi
Thanks for the report.
I'll investigate as soon as I can but I'm pretty busy lately, so I can't really say when

**Comment by nickimola** [comment]
Hi
I apologize for the late release but I'm a bit busy with different side projects.

Anyway, I've just released a new version (2.2) which should solve the issue (thanks to [sarunasdjacenko](https://github.com/sarunasdjacenko) merge request).

It should be available once google reviews it
